version: '2'

services:
  web:
    build: .
    ports:
      - 8000:80
      - 443:443
    volumes:
      - .:/var/www/html
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongodb:/data/db